version: '3.4'

services:
    php:
        build:
            context: .
            target: php
        environment:
            - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
            - XDEBUG_CONFIG=remote_host=host.docker.internal
        volumes:
            - .:/var/www/html:rw,cached
            - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        extra_hosts:
            - "host.docker.internal:$DOCKER_HOST_IP"
    nginx:
        build:
            context: .
            target: nginx
        depends_on:
            - php
        volumes:
            - .:/var/www/html:rw,cached
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"
